ARCH-2011 - Adding status check tests

diff --git a/.github/workflows/build-and-review-pr.yml b/.github/workflows/build-and-review-pr.yml
--- a/.github/workflows/build-and-review-pr.yml
+++ b/.github/workflows/build-and-review-pr.yml
@@ -25,6 +25,11 @@ env:
   EMPTY_SUMMARY_INPUT_FILE: './test/input-files/empty.md'
   COVERAGE_SUMMARY_INPUT_FILE: './test/input-files/coverage-summary.md'
 
+  # FAILING_SUMMARY_INPUT_FILE: './test/input-files/failing.md'
+  # NO_TESTS_SUMMARY_INPUT_FILE: './test/input-files/no-coverage.md'
+
+  # TRUNCATE_SUMMARY_INPUT_FILE: './test/input-files/truncate.md'
+
 jobs:
   build-and-review-pr:
     # This reusable workflow will check to see if an action's source code has changed based on
@@ -73,7 +78,7 @@ jobs:
       FAILING_BRANCH_MD_FILE: './test/expected-markdown/unit-tests/failing-branch.md'
       IGNORE_THRESHOLDS_MD_FILE: './test/expected-markdown/unit-tests/ignore-thresholds.md'
       THRESHOLD_0_MD_FILE: './test/expected-markdown/unit-tests/threshold-0.md'
-      
+
     steps:
       - name: '-------------------------------------------------------------------------------------------------------------'
         run: echo ""
@@ -459,3 +464,271 @@ jobs:
           expectedFileName="${{ env.THRESHOLD_0_MD_FILE }}"
           actualFileName="${{ steps.threshold-0.outputs.coverage-results-file-path }}"
           ./test/assert-file-contents-match.sh --expectedFileName $expectedFileName --actualFileName $actualFileName
+
+  test-status-checks:
+    runs-on: ubuntu-latest
+    env:
+      NO_FAILURES_MD_FILE: './test/expected-markdown/status-checks/no-failures.md'
+      IGNORE_FAILURES_MD_FILE: './test/expected-markdown/status-checks/ignore-failures.md'
+      ALLOW_FAILURES_MD_FILE: './test/expected-markdown/status-checks/allow-failures.md'
+      THRESHOLD_0_MD_FILE: './test/expected-markdown/status-checks/threshold-0.md'
+
+      NO_FAILURES_REPORT_NAME: 'No Threshold Failures Scenario'
+      IGNORE_FAILURES_REPORT_NAME: 'Ignore Threshold Failures Scenario'
+      ALLOW_FAILURES_REPORT_NAME: 'Allow Failures Failures Scenario'
+      THRESHOLD_0_REPORT_NAME: 'Threshold 0 Scenario'
+
+      NO_FAILURES_CHECK_NAME: 'no-failures-check'
+      IGNORE_FAILURES_CHECK_NAME: 'ignore-failures-check'
+      ALLOW_FAILURES_CHECK_NAME: 'allow-failures-check'
+      THRESHOLD_0_CHECK_NAME: 'threshold-0-check'
+
+    steps:
+      - name: '-------------------------------------------------------------------------------------------------------------'
+        run: echo ""
+      - name: '                                                    SETUP                                                    '
+        run: echo ""
+
+      - name: Setup - Fail test job if fork
+        run: |
+          if [ "${{ github.event.pull_request.head.repo.fork }}" == "true" ]; then
+            echo "This test job requires the `checks: write` scope on the GITHUB_TOKEN which PRs from forks do not have.  Before this PR can be merged, the tests should be run on an intermediate branch created by repository owners."
+            exit 1
+          fi
+
+      - name: Setup - Checkout the action
+        uses: actions/checkout@v4
+
+      - name: '-------------------------------------------------------------------------------------------------------------'
+        run: echo ""
+      - name: '                                     TEST 10 - STATUS CHECK - NO FAILURES                                    '
+        run: echo ""
+
+      - name: 10a - When process-code-coverage-summary is called with no threshold failures
+        if: always()
+        id: no-failures
+        uses: ./
+        with:
+          github-token: '${{ secrets.GITHUB_TOKEN }}'
+          summary-file: ${{ env.COVERAGE_SUMMARY_INPUT_FILE }}
+          report-name: ${{ env.NO_FAILURES_REPORT_NAME }}
+          check-name: ${{ env.NO_FAILURES_CHECK_NAME }}
+          create-status-check: true
+          line-threshold: 50 # The actual coverage is 94.4
+          branch-threshold: 50 # The actual coverage is 93.8
+          ignore-threshold-failures: false
+          create-pr-comment: false
+
+      - name: 10b - Then the action outcome should be success
+        if: always()
+        run: ./test/assert-values-match.sh --name "step outcome" --expected "success" --actual "${{ steps.no-failures.outcome }}"
+
+      - name: 10c - And the status-check-id output should be populated
+        if: always()
+        run: ./test/assert-value-is-not-empty.sh --name "status-check-id output" --value "${{ steps.no-failures.outputs.status-check-id }}"
+
+      - name: 10d - And the coverage-outcome output should be Passed
+        if: always()
+        run: ./test/assert-values-match.sh --name "coverage-outcome output" --expected "Passed" --actual "${{ steps.no-failures.outputs.coverage-outcome }}"
+
+      - name: 10e - And the status check should match the inputs
+        if: always()
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const fs = require('fs');
+            const assertStatusCheckExists = require('./test/assert-status-check-exists.js');
+            const assertStatusCheckMatchesExpectations = require('./test/assert-status-check-matches-expectations.js');
+
+            const checkId = '${{ steps.no-failures.outputs.status-check-id }}';
+            const actualCheck = await assertStatusCheckExists(github, context, core, checkId);
+            const expectedBody = fs.readFileSync('${{ env.NO_FAILURES_MD_FILE }}', 'utf8');
+
+            const expectedValues = {
+              name: 'status check - ${{ env.NO_FAILURES_CHECK_NAME }}'.toLowerCase(),
+              status: 'completed',
+              conclusion: 'success',
+              title: '${{ env.NO_FAILURES_REPORT_NAME }}',
+              text: expectedBody
+            };
+            assertStatusCheckMatchesExpectations(core, actualCheck, expectedValues);
+
+      - name: '-------------------------------------------------------------------------------------------------------------'
+        run: echo ""
+      - name: '                                   TEST 11 - STATUS CHECK - IGNORE FAILURES                                  '
+        run: echo ""
+
+      - name: 11a - When process-code-coverage-summary is called with threshold failures & ignore-threshold-failures=true
+        if: always()
+        id: ignore-failures
+        uses: ./
+        with:
+          github-token: '${{ secrets.GITHUB_TOKEN }}'
+          summary-file: ${{ env.COVERAGE_SUMMARY_INPUT_FILE }}
+          report-name: ${{ env.IGNORE_FAILURES_REPORT_NAME }}
+          check-name: ${{ env.IGNORE_FAILURES_CHECK_NAME }}
+          create-status-check: true
+          line-threshold: 99 # The actual coverage is 94.4
+          branch-threshold: 99 # The actual coverage is 93.8
+          ignore-threshold-failures: true
+          create-pr-comment: false
+
+      - name: 11b - Then the action outcome should be success
+        if: always()
+        run: ./test/assert-values-match.sh --name "step outcome" --expected "success" --actual "${{ steps.ignore-failures.outcome }}"
+
+      - name: 11c - And the status-check-id output should be populated
+        if: always()
+        run: ./test/assert-value-is-not-empty.sh --name "status-check-id output" --value "${{ steps.ignore-failures.outputs.status-check-id }}"
+
+      - name: 11d - And the coverage-outcome output should be Failed
+        if: always()
+        run: ./test/assert-values-match.sh --name "coverage-outcome output" --expected "Failed" --actual "${{ steps.ignore-failures.outputs.coverage-outcome }}"
+
+      - name: 11e - And the status check should match the inputs
+        if: always()
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const fs = require('fs');
+            const assertStatusCheckExists = require('./test/assert-status-check-exists.js');
+            const assertStatusCheckMatchesExpectations = require('./test/assert-status-check-matches-expectations.js');
+
+            const checkId = '${{ steps.ignore-failures.outputs.status-check-id }}';
+            const actualCheck = await assertStatusCheckExists(github, context, core, checkId);
+            const expectedBody = fs.readFileSync('${{ env.IGNORE_FAILURES_MD_FILE }}', 'utf8');
+
+            const expectedValues = {
+              name: 'status check - ${{ env.IGNORE_FAILURES_CHECK_NAME }}'.toLowerCase(),
+              status: 'completed',
+              conclusion: 'neutral',
+              title: '${{ env.IGNORE_FAILURES_REPORT_NAME }}',
+              text: expectedBody
+            };
+            assertStatusCheckMatchesExpectations(core, actualCheck, expectedValues);
+
+      - name: '-------------------------------------------------------------------------------------------------------------'
+        run: echo ""
+      - name: '                                    TEST 12 - STATUS CHECK - ALLOW FAILURES                                    '
+        run: echo ""
+
+      - name: 12a - When process-code-coverage-summary is called with threshold failures & ignore-threshold-failures=false
+        if: always()
+        id: allow-failures
+        uses: ./
+        with:
+          github-token: '${{ secrets.GITHUB_TOKEN }}'
+          summary-file: ${{ env.COVERAGE_SUMMARY_INPUT_FILE }}
+          report-name: ${{ env.ALLOW_FAILURES_REPORT_NAME }}
+          check-name: ${{ env.ALLOW_FAILURES_CHECK_NAME }}
+          create-status-check: true
+          line-threshold: 99 # The actual coverage is 94.4
+          branch-threshold: 99 # The actual coverage is 93.8
+          ignore-threshold-failures: false
+          create-pr-comment: false
+
+      - name: 12b - Then the action outcome should be success
+        if: always()
+        run: ./test/assert-values-match.sh --name "step outcome" --expected "success" --actual "${{ steps.allow-failures.outcome }}"
+
+      - name: 12c - And the status-check-id output should be populated
+        if: always()
+        run: ./test/assert-value-is-not-empty.sh --name "status-check-id output" --value "${{ steps.allow-failures.outputs.status-check-id }}"
+
+      - name: 12d - And the coverage-outcome output should be Failed
+        if: always()
+        run: ./test/assert-values-match.sh --name "coverage-outcome output" --expected "Failed" --actual "${{ steps.allow-failures.outputs.coverage-outcome }}"
+
+      - name: 12e - And the status check should match the inputs
+        if: always()
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const fs = require('fs');
+            const assertStatusCheckExists = require('./test/assert-status-check-exists.js');
+            const assertStatusCheckMatchesExpectations = require('./test/assert-status-check-matches-expectations.js');
+
+            const checkId = '${{ steps.allow-failures.outputs.status-check-id }}';
+            const actualCheck = await assertStatusCheckExists(github, context, core, checkId);
+            const expectedBody = fs.readFileSync('${{ env.ALLOW_FAILURES_MD_FILE }}', 'utf8');
+
+            const expectedValues = {
+              name: 'status check - ${{ env.ALLOW_FAILURES_CHECK_NAME }}'.toLowerCase(),
+              status: 'completed',
+              conclusion: 'failure',
+              title: '${{ env.ALLOW_FAILURES_REPORT_NAME }}',
+              text: expectedBody
+            };
+            assertStatusCheckMatchesExpectations(core, actualCheck, expectedValues);
+
+      - name: '-------------------------------------------------------------------------------------------------------------'
+        run: echo ""
+      - name: '                                TEST 13 - STATUS CHECK - THRESHOLDS SET TO 0                                 '
+        run: echo ""
+
+      - name: 13a - When process-code-coverage-summary is called with the thresholds set to 0
+        if: always()
+        id: threshold-0
+        uses: ./
+        with:
+          github-token: '${{ secrets.GITHUB_TOKEN }}'
+          summary-file: ${{ env.COVERAGE_SUMMARY_INPUT_FILE }}
+          report-name: ${{ env.THRESHOLD_0_REPORT_NAME }}
+          check-name: ${{ env.THRESHOLD_0_CHECK_NAME }}
+          create-status-check: true
+          line-threshold: 0 # The actual coverage is 94.4
+          branch-threshold: 0 # The actual coverage is 93.8
+          ignore-threshold-failures: false
+          create-pr-comment: false
+
+      - name: 13b - Then the action outcome should be success
+        if: always()
+        run: ./test/assert-values-match.sh --name "step outcome" --expected "success" --actual "${{ steps.threshold-0.outcome }}"
+
+      - name: 13c - And the status-check-id output should be populated
+        if: always()
+        run: ./test/assert-value-is-not-empty.sh --name "status-check-id output" --value "${{ steps.threshold-0.outputs.status-check-id }}"
+
+      - name: 13d - And the coverage-outcome output should be Passed
+        if: always()
+        run: ./test/assert-values-match.sh --name "coverage-outcome output" --expected "Passed" --actual "${{ steps.threshold-0.outputs.coverage-outcome }}"
+
+      - name: 13e - And the status check should match the inputs
+        if: always()
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const fs = require('fs');
+            const assertStatusCheckExists = require('./test/assert-status-check-exists.js');
+            const assertStatusCheckMatchesExpectations = require('./test/assert-status-check-matches-expectations.js');
+
+            const checkId = '${{ steps.threshold-0.outputs.status-check-id }}';
+            const actualCheck = await assertStatusCheckExists(github, context, core, checkId);
+            const expectedBody = fs.readFileSync('${{ env.THRESHOLD_0_MD_FILE }}', 'utf8');
+
+            const expectedValues = {
+              name: 'status check - ${{ env.THRESHOLD_0_CHECK_NAME }}'.toLowerCase(),
+              status: 'completed',
+              conclusion: 'neutral',
+              title: '${{ env.THRESHOLD_0_REPORT_NAME }}',
+              text: expectedBody
+            };
+            assertStatusCheckMatchesExpectations(core, actualCheck, expectedValues);
+
+      - name: '-------------------------------------------------------------------------------------------------------------'
+        run: echo ""
+      - name: '                                                   TEARDOWN                                                  '
+        run: echo ""
+
+      - name: Teardown - Modify failing Status Check conclusion
+        if: always()
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const fs = require('fs');
+            const updateFailingStatusCheck = require('./test/update-failing-status-check.js');
+
+            await updateFailingStatusCheck(github, context, core, '${{ steps.allow-failures.outputs.status-check-id }}');
+
+      - name: '-------------------------------------------------------------------------------------------------------------'
+        run: echo ""
